version: "3.7"

#services:
#  traefik:
#    image: traefik
##    command: --docker
#    restart: always
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    - ./traefik/conf/traefik.toml:/traefik.toml
#    - ./traefik/acme/acme.json:/acme.json
#    ports:
#    - 80:80
#    - 443:443
#    - 8080:8080
#    networks:
#    - proxy
#    container_name: traefik

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/conf/traefik.toml:/traefik.toml
      - ./traefik/acme/acme.json:/acme.json

    container_name: traefik


networks:
  proxy:
    external: true
    name: proxy